// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4k-XCRRSc_cn_a3i8ceZpseKi6-MUMY8',
    appId: '1:938095179454:web:1a3907cb5f73bbfc49d0ef',
    messagingSenderId: '938095179454',
    projectId: 'proyecto-firebase-trivia-anime',
    authDomain: 'proyecto-firebase-trivia-anime.firebaseapp.com',
    storageBucket: 'proyecto-firebase-trivia-anime.firebasestorage.app',
    measurementId: 'G-CRZZZ68P2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoAEwEvFHxLQSQ5meXoZMPxzfnOdHqjTY',
    appId: '1:938095179454:android:c2e6a776360c975549d0ef',
    messagingSenderId: '938095179454',
    projectId: 'proyecto-firebase-trivia-anime',
    storageBucket: 'proyecto-firebase-trivia-anime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyNxBsiRmWjnyGmJtD83Vp041bAfpVBI',
    appId: '1:938095179454:ios:1143ac209ce0b78449d0ef',
    messagingSenderId: '938095179454',
    projectId: 'proyecto-firebase-trivia-anime',
    storageBucket: 'proyecto-firebase-trivia-anime.firebasestorage.app',
    iosBundleId: 'com.example.flutterTriviaAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyNxBsiRmWjnyGmJtD83Vp041bAfpVBI',
    appId: '1:938095179454:ios:1143ac209ce0b78449d0ef',
    messagingSenderId: '938095179454',
    projectId: 'proyecto-firebase-trivia-anime',
    storageBucket: 'proyecto-firebase-trivia-anime.firebasestorage.app',
    iosBundleId: 'com.example.flutterTriviaAnime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4k-XCRRSc_cn_a3i8ceZpseKi6-MUMY8',
    appId: '1:938095179454:web:522d458f97a8cf6749d0ef',
    messagingSenderId: '938095179454',
    projectId: 'proyecto-firebase-trivia-anime',
    authDomain: 'proyecto-firebase-trivia-anime.firebaseapp.com',
    storageBucket: 'proyecto-firebase-trivia-anime.firebasestorage.app',
    measurementId: 'G-J636XK30Y3',
  );

}